### ISSUE TITLE
Revert reduction in Julia build script

### ISSUE THREAD

**Issue by Moelf** [ivukotic/ml_platform#28]
A bunch of packages are deleted in https://github.com/ivukotic/ml_platform/commit/d56ea9089b748a4e9cf1281fb0d8cbccb0df7c67

can we revert that?

**Comment by Moelf** [comment]
Currently not all of them, but at least we should have uproot and RISE.

In general I want to avoid people switching between Python and Julia image just to find something is missing.

**Comment by ivukotic** [comment]
let me try putting them back.

**Comment by ivukotic** [comment]
something strange is going on. image is built correctly. Upload of the image to dockerhub works fine, but to harbor it fails without any output. Maybe we should move to using docker image...

**Comment by Moelf** [comment]
interesting....
