### ISSUE TITLE
Build failure for Julia on Harbor

### ISSUE THREAD

**Issue by Moelf** [ivukotic/ml_platform#32]
https://github.com/ivukotic/ml_platform/actions/runs/11254393804/job/31291702192

not sure what happened, there's not much in the log

**Comment by ivukotic** [comment]
Hi,

I am not sure either. I just started a re-run of the build action.

Ilija


From: Jerry Ling ***@***.***>
Sent: Friday, October 11, 2024 06:52
To: ivukotic/ml_platform ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ivukotic/ml_platform] Build failure for Julia on Harbor (Issue #32)


https://github.com/ivukotic/ml_platform/actions/runs/11254393804/job/31291702192<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/actions/runs/11254393804/job/31291702192__;!!BpyFHLRN4TMTrA!8OjZCMb1MImOmnDbMpbc1Q0L3cZIddGw5beBazFV9MCLlG2KO3sT6dKOf64pwmH8M4YDK2E9c7BvsOItArWn8QfmD7A0$>

not sure what happened, there's not much in the log

**Comment by ivukotic** [comment]
It failed again without logs after more than 6h …

No idea…


From: Jerry Ling ***@***.***>
Sent: Friday, October 11, 2024 06:52
To: ivukotic/ml_platform ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ivukotic/ml_platform] Build failure for Julia on Harbor (Issue #32)


https://github.com/ivukotic/ml_platform/actions/runs/11254393804/job/31291702192<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/actions/runs/11254393804/job/31291702192__;!!BpyFHLRN4TMTrA!8OjZCMb1MImOmnDbMpbc1Q0L3cZIddGw5beBazFV9MCLlG2KO3sT6dKOf64pwmH8M4YDK2E9c7BvsOItArWn8QfmD7A0$>

not sure what happened, there's not much in the log

**Comment by Moelf** [comment]
I'm wondering what has diverged between julia and the "base" version, maybe it's worth "rebaseing" Julia branch on top of that?

**Comment by ivukotic** [comment]
I don't see what is the difference between runner that sends to harbor and one sending to dockerhub. I could manually push the image that was built for harbor, but it would be better to understand the issue.

**Comment by Moelf** [comment]
Oh didn't realize it's failing again

**Comment by ivukotic** [comment]
only the one sending to harbor. the one sending to dockerhub worked fine. Now trying to find why.

**Comment by ivukotic** [comment]
finally fixed. harbor robot username has a "$" and it required a \ in front of it.
